INSERT INTO encounters (id, name, created_at, updated_at) VALUES
	(1, 'Encounter 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(2, 'Encounter 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(3, 'Encounter 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(4, 'Encounter 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(5, 'Encounter 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
